"""add timestamp

Revision ID: 7fbf127dc198
Revises: dcc9f40cf33e
Create Date: 2024-11-27 22:07:31.801716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbf127dc198'
down_revision: Union[str, None] = 'dcc9f40cf33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_tracks', sa.Column('liked_at', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liked_tracks', 'liked_at')
    # ### end Alembic commands ###
