"""add description

Revision ID: cbd0659bc16a
Revises: 54e1a6d2feac
Create Date: 2024-11-26 23:33:32.252171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd0659bc16a'
down_revision: Union[str, None] = '54e1a6d2feac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_tracks', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liked_tracks', 'description')
    # ### end Alembic commands ###
