"""add track state

Revision ID: dcc9f40cf33e
Revises: cbd0659bc16a
Create Date: 2024-11-27 21:59:06.532490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc9f40cf33e'
down_revision: Union[str, None] = 'cbd0659bc16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_tracks', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liked_tracks', 'state')
    # ### end Alembic commands ###
